[package]
name = "rhkb"
version = "1.0.0"
authors = ["Léo Duret <leoduret@outlook.com>"]

[dependencies]
x11 = {version = "^2.18", features=["xlib"]}
libc = {version = "^0.2"}
fst = {version = "^0.4"}
memmap = {version = "^0.7"}
zombie = {version = "^0.0.4"}
